#pragma once

namespace ManiaPlanet
{

    class CGameCtnCursor;
    class CGameCtnEditorCommonInterface;

    class CGameCtnEditor : public CMwNod
    {
    public:
        #include "Generated/CGameCtnEditor.Generated.h"

        virtual void            m50                     () = 0;
        virtual void            m54                     () = 0;
        virtual void            m58                     () = 0;
        virtual void            m5C                     () = 0;
        virtual void            m60                     () = 0;
        virtual void            m64                     () = 0;
        virtual void            m68                     () = 0;
        virtual void            m6C                     () = 0;
        virtual void            m70                     () = 0;
        virtual void            m74                     () = 0;
        virtual void            m78                     () = 0;
        virtual void            m7C                     () = 0;
        virtual void            m80                     () = 0;
        virtual void            m84                     () = 0;
        virtual void            m88                     () = 0;
        virtual void            m8C                     () = 0;
        virtual void            m90                     () = 0;
        virtual void            m94                     () = 0;
        virtual void            m98                     () = 0;
        virtual void            m9C                     () = 0;
        virtual void            ProcessInput            ( void* pInputInfo ) = 0;
        virtual void            mA4                     () = 0;
        virtual void            mA8                     () = 0;
        virtual void            mAC                     () = 0;
        virtual void            mB0                     () = 0;
        virtual void            mB4                     () = 0;
        virtual void            mB8                     () = 0;
        virtual void            mBC                     () = 0;
        virtual void            mC0                     () = 0;
        virtual void            mC4                     () = 0;
        virtual void            mC8                     () = 0;
        virtual void            mCC                     () = 0;
        virtual void            mD0                     () = 0;
        virtual void            ApplyCursorSettings     ( void* pCursorSettings ) = 0;
        virtual void            mD8                     () = 0;
        virtual void            mDC                     () = 0;
        virtual void            mE0                     () = 0;
        virtual void            mE4                     () = 0;
        virtual void            mE8                     () = 0;
        virtual void            mEC                     () = 0;
        virtual void            mF0                     () = 0;
        virtual void            GetBlockGroundModeAndVariantWithError   ( CGameCtnBlockInfo* pBlockInfo, uint3 vecPos, int iDir, bool* pbGround, int* piVariant, StringW* pwstrError, int iUnknown ) = 0;
        virtual CGameCtnBlock*  PlaceBlock              ( CGameCtnBlockInfo* pBlockInfo, CGameCtnBlockSkin* pSkin, uint3 vecPos, int iDir, int iSubVariant, int iUnknown1, bool bCorrectRoadConnections, bool bCreatePillars, int iUnknown2, bool bGround, int iVariant ) = 0;
        virtual void            PlaceBlockWithAutoGroundAndVariant      ( CGameCtnBlockInfo* pBlockInfo, CGameCtnBlockSkin* pSkin, uint3 vecPos, int iDir, int iSubVariant, int iUnknown1, int iUnknown2, int iUnknown3, int iUnknown4, bool bGround, int iVariant ) = 0;
        virtual void            RemoveBlockSafe         ( CGameCtnBlock* pBlock, int iUnknown ) = 0;
        virtual void            RemoveBlock             ( CGameCtnBlock* pBlock, int iUnknown1, int iUnknown2 ) = 0;
        virtual void            m108                    () = 0;
        virtual void            CreatePillars           () = 0;

        void                    AddBlock                ( CGameCtnBlockInfo* pBlock, CGameCtnBlockSkin* pSkin, uint3 vecPos, int iDir, bool bGround, int iVariant, int iSubVariant, int iUnknown1, int iUnknown2 );

    private:
        void*               m_pScene;
        void*               m_pCamera;
        uint                m_pInputPort;
        uint                m_field24;
        uint                m_field28;
        uint                m_field2C;
        uint                m_field30;
        uint                m_field34;
        uint                m_field38;
        uint                m_field3C;
        uint                m_field40;
        uint                m_field44;
        uint                m_field48;
        uint                m_field4C;
        uint                m_field50;
        uint                m_field54;
        uint                m_field58;
        uint                m_field5C;
        uint                m_field60;
        uint                m_field64;
        uint                m_field68;
        uint                m_field6C;
        uint                m_field70;
        uint                m_field74;
        uint                m_field78;
        List < void* >      m_field7C;
        List < void* >      m_EditorPlugins;
        uint                m_field94;
        uint                m_field98;
        uint                m_field9C;
        uint                m_fieldA0;
        uint                m_fieldA4;
        uint                m_fieldA8;
        uint                m_fieldAC;
        void*               m_pFrameRoot;
        uint                m_fieldB4;
        uint                m_fieldB8;
        uint                m_fieldBC;
        uint                m_fieldC0;
        uint                m_fieldC4;
        uint                m_fieldC8;
        uint                m_fieldCC;
        uint                m_fieldD0;
        uint                m_fieldD4;
        uint                m_fieldD8;
        uint                m_fieldDC;
        uint                m_fieldE0;
        uint                m_fieldE4;
        uint                m_fieldE8;
        uint                m_fieldEC;
        uint                m_fieldF0;
        uint                m_fieldF4;
        uint                m_fieldF8;
        uint                m_fieldFC;
        uint                m_field100;
        uint                m_field104;
        uint                m_field108;
        uint                m_field10C;
        uint                m_field110;
        uint                m_field114;
        uint                m_field118;
        uint                m_field11C;
        uint                m_field120;
        uint                m_field124;
        uint                m_field128;
        uint                m_field12C;
        uint                m_field130;
        uint                m_field134;
        uint                m_field138;
        uint                m_field13C;
        uint                m_field140;
        uint                m_field144;
        uint                m_field148;
        uint                m_field14C;
        uint                m_field150;
        uint                m_field154;
        uint                m_field158;
        uint                m_field15C;
        uint                m_field160;
        uint                m_field164;
        uint                m_field168;
        uint                m_field16C;
        uint                m_field170;
        uint                m_field174;
        uint                m_field178;
        uint                m_field17C;
        uint                m_field180;
        uint                m_field184;
        CGameCtnChallenge*  m_pChallenge;
        uint                m_field18C;
        void*               m_pControlCameraEditorOrbital;
        CGameCtnBlockInfo*  m_pCurrentBlockInfo;
        uint                m_field198;
        uint                m_field19C;
        uint                m_field1A0;
        uint                m_field1A4;
        uint                m_field1A8;
        uint                m_field1AC;
        uint                m_field1B0;
        uint                m_field1B4;
        uint                m_field1B8;
        uint                m_field1BC;
        uint                m_field1C0;
        uint                m_field1C4;
        uint                m_field1C8;
        uint                m_field1CC;
        uint                m_field1D0;
        uint                m_field1D4;
        uint                m_field1D8;
        uint                m_field1DC;
        uint                m_field1E0;
        uint                m_field1E4;
        uint                m_field1E8;
        uint                m_field1EC;
        uint                m_field1F0;
        uint                m_field1F4;
        uint                m_field1F8;
        uint                m_field1FC;
        uint                m_field200;
        uint                m_field204;
        uint                m_field208;
        uint                m_field20C;
        uint                m_field210;
        uint                m_field214;
        uint                m_field218;
        uint                m_field21C;
        uint                m_field220;
        uint                m_field224;
        uint                m_field228;
        uint                m_field22C;
        uint                m_field230;
        uint                m_field234;
        uint                m_field238;
        CGameCtnEditorCommonInterface*   m_pEditorCommonInterface;
        CGameCtnCursor*     m_pCursor;
        uint                m_field244;
        uint                m_field248;
        uint                m_field24C;
        uint                m_field250;
        uint                m_field254;
        uint                m_field258;
        uint                m_field25C;
        uint                m_field260;
        uint                m_field264;
        uint                m_field268;
        uint                m_field26C;
        uint                m_field270;
        uint                m_field274;
        uint                m_field278;
        uint                m_field27C;
        uint                m_field280;
        uint                m_field284;
        uint                m_field288;
        uint                m_field28C;
        uint                m_field290;
        uint                m_field294;
        uint                m_field298;
        uint                m_field29C;
        uint                m_field2A0;
        uint                m_field2A4;
        uint                m_field2A8;
        uint                m_field2AC;
        uint                m_field2B0;
        uint                m_field2B4;
        uint                m_field2B8;
        uint                m_field2BC;
        uint                m_field2C0;
        uint                m_field2C4;
        uint                m_field2C8;
        uint                m_field2CC;
        uint                m_field2D0;
        uint                m_field2D4;
        uint                m_field2D8;
        uint                m_field2DC;
        uint                m_field2E0;
        uint                m_field2E4;
        uint                m_field2E8;
        uint                m_field2EC;
        uint                m_field2F0;
        uint                m_field2F4;
        uint                m_field2F8;
        uint                m_field2FC;
        uint                m_field300;
        uint                m_field304;
        uint                m_field308;
        uint                m_field30C;
        uint                m_field310;
        uint                m_field314;
        uint                m_field318;
        uint                m_field31C;
        uint                m_field320;
        uint                m_field324;
        uint                m_field328;
        uint                m_field32C;
        uint                m_field330;
        uint                m_field334;
        uint                m_field338;
        uint                m_field33C;
        uint                m_field340;
        uint                m_field344;
        uint                m_field348;
        uint                m_field34C;
        uint                m_field350;
        uint                m_field354;
        uint                m_field358;
        uint                m_field35C;
        uint                m_field360;
        uint                m_field364;
        uint                m_field368;
        uint                m_field36C;
        uint                m_field370;
        uint                m_field374;
        uint                m_field378;
        uint                m_field37C;
        uint                m_field380;
        uint                m_field384;
        uint                m_field388;
        uint                m_field38C;
        uint                m_field390;
        uint                m_field394;
        uint                m_field398;
        uint                m_field39C;
        uint                m_field3A0;
        uint                m_field3A4;
        uint                m_field3A8;
        uint                m_field3AC;
        uint                m_field3B0;
        uint                m_field3B4;
        uint                m_field3B8;
        uint                m_field3BC;
        uint                m_field3C0;
        uint                m_field3C4;
        uint                m_field3C8;
        uint                m_field3CC;
        uint                m_field3D0;
        uint                m_field3D4;
        uint                m_field3D8;
        uint                m_field3DC;
        uint                m_field3E0;
        uint                m_field3E4;
        uint                m_bDisableSnapToGround;
        uint                m_field3EC;
        uint                m_field3F0;
        uint                m_bPlacingUndergroundBlock;
    };

}
